# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'corne'
on: 
   push: 
     branches: [ "master" ] 
   pull_request: 
     branches: [ "master" ] 
   workflow_dispatch: 
 
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nrfmicro_13"]'
      shield: '["corne_left nice_view_adapter nice_view","corne_right nice_view_adapter nice_view"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y\nCONFIG_ZMK_RGB_UNDERGLOW=y\nCONFIG_WS2812_STRIP=y\nCONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y\nCONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y\nCONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000\nCONFIG_BT_CTLR_TX_PWR_PLUS_8=y\nCONFIG_ZMK_DISPLAY=y\nCONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n\nCONFIG_ZMK_WIDGET_BATTERY_STATUS=y"]'
      branches: '["zmkfirmware/zmk/main urob/zmk/mouse-3.2"]'
