# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'corne'
on: 
   push: 
     branches: [ "master" ] 
   pull_request: 
     branches: [ "master" ] 
   workflow_dispatch: 
 
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nrfmicro_13"]'
      shield: '["corne_left","corne_right"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR\n#define MIRYOKU_KLUDGE_TOPROWCOMBOS"]'
      branches: '["zmkfirmware/zmk/main urob/zmk/mouse-3.2"]'
